services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_SERVERS: zookeeper:2888:3888
        ports:
            - 2181:2181
        networks: 
            - kafka-ms-api-gtwy  
  
    kafka:
        image: confluentinc/cp-kafka:latest
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://192.168.220.128:9092
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks: 
            - kafka-ms-api-gtwy  
      
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        networks: 
            - kafka-ms-api-gtwy 
        depends_on:
            - kafka
        ports:
            - 19000:9000
        environment:
            #KAFKA_BROKERCONNECT: kafka:29092      
            KAFKA_BROKERCONNECT: kafka:9092      
      
      
networks: 
  kafka-ms-api-gtwy:
    driver: bridge        